name: Build and Archive Hashcat (Linux)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-hashcat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hashcat source
        uses: actions/checkout@v4
        with:
          repository: hashcat/hashcat
          path: hashcat

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ocl-icd-opencl-dev zip

      - name: Build hashcat
        run: |
          cd hashcat
          make

      - name: Archive hashcat
        run: |
          zip -r hashcat-latest.zip hashcat

      - name: Upload hashcat archive
        uses: actions/upload-artifact@v4
        with:
          name: hashcat-latest
          path: hashcat-latest.zip
